-- Utility functions for the cutout limiter Lua scripts.
-- Each script sent to Redis will have this pre-appended to it in python.

local function prune_expired(events_key, counts_key, now, window)
    -- Prune expired jobs and their corresponding cutout counts.

    local cutoff = now - window
    local expired = redis.call('ZRANGE', events_key, '-inf', cutoff, 'BYSCORE')
    if #expired > 0 then
        redis.call('ZREMRANGEBYSCORE', events_key, '-inf', cutoff)
        for _, job_id in ipairs(expired) do
            redis.call('HDEL', counts_key, job_id)
        end
    end
end

local function sum_cutout_counts(events_key, counts_key, now, window)
    -- Return the total number of cutouts generated by all jobs in the window.

    -- Prune expired jobs before summing.
    prune_expired(events_key, counts_key, now, window)

    local total = 0
    local counts = redis.call('HVALS', counts_key)
    for _, v in ipairs(counts) do
        total = total + tonumber(v)
    end

    return total
end

local function oldest_event_score(events_key)
    -- Return the score (timestamp) of the oldest event in the window.
    local oldest = redis.call('ZRANGE', events_key, 0, 0, 'WITHSCORES')
    if #oldest > 0 then
        return tonumber(oldest[2])
    end
    return 0
end

local function add_reservation(events_key, counts_key, job_id, count, now, window)
    -- Add a job's reservation and its corresponding cutout count.
    redis.call('ZADD', events_key, now, job_id)
    redis.call('HSET', counts_key, job_id, count)
    local ttl = window * 2
    redis.call('EXPIRE', events_key, ttl)
    redis.call('EXPIRE', counts_key, ttl)
end

local function drop_reservation(events_key, counts_key, job_id)
    -- Drop a job's reservation and its corresponding cutout count.
    redis.call('ZREM', events_key, job_id)
    redis.call('HDEL', counts_key, job_id)
end
